shell.go

So I can find the local peer's ID for IPNS references.  The
/ipns/local resolution is specific to the FUSE implementation, so it
doesn't work directly with the non-FUSE commands:
$ ipfs ls /ipns/local
Error: could not resolve name.
This shell function allows me to figure out what to put in:
$ ipfs ls /inps/<local-ID>
And while we're at it, we also support ID queries on other peers via a
variadic argument.

Add Shell.ID() and Shell.ID(peer)

---

shell.go
unixfs.go

@cryptix does this fix your issues?

fix list commands

---

shell.go

Fix argument order in Patch, PatchLink

---

README.md

Added installation note

---

.travis.yml
shell.go

deps: point multiaddr imports to multiformats org

---

shell.go

License: MIT
Signed-off-by: Iaroslav Gridin <voker57@gmail.com>

Add raw-leaves option to AddWithOpts and expose it

---

dag.go
shell_test.go

Fix overlooked import

---

shell.go

Just ran
gofmt -w .
on the project root. That's all. Helps with legibility.

all: gofmt

---

.gx/lastpubver
package.json

Alignment to deps used in our gx dep trees.

gx publish 1.3.3

---

.gx/lastpubver
package.json

gx publish 1.3.4

---

shell.go

fix typed-nil error

---

README.md

docs: add an example

---

.gx/lastpubver
package.json

gx publish 1.4.1

---

.gx/lastpubver
package.json

gx publish 1.4.2

---

shell.go

fixes https://github.com/ipfs/go-ipfs-api/pull/160/files#r253793845

use the passed http client

---

.gx/lastpubver
package.json

Gx dependency alignment with latest go-ipfs/libp2p... to eliminate dupes.

gx publish 1.4.6

---

.gx/lastpubver
package.json

gx publish 1.4.7

---

README.md

Related to https://github.com/ipfs/go-ipfs-api/issues/147

Update project description in readme

---

mfs.go
mfs_test.go

PR for #215 
Maybe also covered #189

Add files api

---

key.go
key_test.go

Refer to the document [here](https://docs.ipfs.io/reference/http/api/#api-v0-key-gen)

Implement the key related apis

---

add.go

Just thought it would be good to have docs for such an important method.

Added missing docs for Add method

---

go.mod
go.sum
shell.go

chore: switch tar-utils to boxo variant

---

version.json

Would prefer a 0.6.2, but since we updated some dependencies, stuff can break for other people.

chore: version 0.7.0

---

README.md

docs: deprecate message
