- shell.go
We want to distinguish between the command (e.g. 'cat') and the
arguments (e.g. '/ipfs/QmSomeHash').  This updates NewRequest calls to
match the fingerprint from go-ipfs's commands/request.go:
func NewRequest(path []string, opts OptMap, args []string, file files.File, cmd *Command, optDefs map[string]Option) (Request, error)
Before this commit, Shell.Cat would produce URLs like:
/api/v0/cat//ipfs/QmSomeHash&enc=json&stream=-
which generate 301 redirects (that aren't followed) to remove the
`//`.  After this commit, Shell.Cat produces URLs like:
/api/v0/cat?arg=%2Fipfs%2FQmSomeHash
which works as expected.
> Update NewRequest() calls to separate the path from the args

- ipns.go
I've spun the IPNS layer off into it's own file to avoid crowding
shell.go.
Depends on the currently-unmerged ipfs/go-ipfs#1397.
> Add Shell.Publish(node, value)

- unixfs.go
So I can bind to the Unix-filesystem-layer version of ls that landed
with [1].  I've spun this layer off into it's own file to avoid
crowding shell.go.
[1]: https://github.com/ipfs/go-ipfs/pull/1348
> Add Shell.FileList(path)

- request.go
- shell.go
beb4a5c: shell `Cat()` returns an io.ReadCloser to remove buffering and make the error visible
0d307b5: `Request.Send()` printed to stdout in an unhanded switch case
> ReadCloser and Response Error handling

- ipns.go
Otherwise, error will not evaluate to nil unless casted to *shell.Error
> Convert *shell.Error to error before returning it

- .travis.yml
- README.md
- shell_test.go
How do you guys feel about this testing setup?
Using the example data feels a bit wonky. For Travis we should probably use a specific version of the docker image then.
@jbenet i couldn't enable travis for this repo because i don't have admin rights.
> initial testing setup

- .travis.yml
- pubsub.go
- shell.go
- shell_test.go
Recently I put a lot of effort into making things smooth on the server side. Here is the API code, that ignores the first packet sent because it is only used to force a flush.
Maybe the pubsub test should not be run if the server is not started with pubsub enabled? Don't know how to check that though.
> Proper Pubsub support

- README.md
While I could list all of the available methods, I think that the GoDocs already do this fairly well and I would be duplicating data. However, a tracking issue with all of the methods that are needed would be ace. Shall I set one of those up?
I also point to the spec here. If someone points me to a Go package with a good Usage and API section, I am happy to fill this out more; however, I am not sure how else to best go forth with filling this section out.
Related to https://github.com/ipfs/go-ipfs-api/issues/13 and https://github.com/ipfs/go-ipfs-api/issues/15.
> Fill out Usage section

- shell.go
- shell_test.go
I had this around since early october. Guess it doesn't hurt to upstream it.
> shell.go: add ObjectStat support

- shell.go
> pubsub/pub TCP未关闭

- README.md
I'm not sure if this was a typo or if it was renamed in /specs/ but the current link does not resolve. I'm assuming this was the intentional url.
> Change spec url

- package.json
- pubsub.go
By using the extracted pubsub protobufs from go-libp2p-pubsub
> Shrink the dependency tree

- pubsub.go
Fixes pubsub after https://github.com/ipfs/go-ipfs/pull/4402 is in.
Before the commands rewrite we made go-ipfs send out the http response immediately by first sending an empty pubsub message. It was only there to force flushing the http connection. This message was discarded on the go-ipfs-api side.
Now go-ipfs uses the new cmds library. We can now properly flush and got rid of this hack. Therefore we mustn't drop the first message anymore.
@diasdavid I presume you'll have to make this change to js-ipfs-api as well?
> pubsub: undo workaround of skipping first message

- bootstrap.go
- shell.go
Add http.ProxyFromEnvironment to the underlying http.Transport of Shell, in order to uses HTTP proxies as directed by the $HTTP_PROXY and $NO_PROXY (or $http_proxy and $no_proxy) environment variables.
> Add http.ProxyFromEnvironment to the underlying http.Transport of Shell

- ipns.go
- ipns_test.go
- request.go
- shell.go
Hello,
I recently ran into an issue with go-ipfs-api where I wanted additional control over IPNS record publishing (key specification, ttl, etc..., retrieving the response) so I have created an additional function `PublishWithDetails`, which returns the response from the IPFS daemon as well as allows for manipulation of the api parameters.
> Add additional publish function for more fine grained control of IPNS record publishing

- ipns.go
When trying to resolve an ipfs hash it fails but ipns works as expected, so I guess this is a typo
> Correct typo ipfs => ipns

- shell.go
> Switch ResolvePath to use /resolve

- shell.go
Block put is pretty much useless without these options so, IMO, breaking this isn't an issue.
> Add options to block put

- bootstrap.go
- dag.go
- ipns.go
- package.json
- request.go
- requestbuilder.go
- requestbuilder_test.go
- shell.go
- shell_test.go
- unixfs.go
An extension/replacement of #98 that allows specifying options. The last commit in this PR replaces uses of `newRequest` with the new builder (removing a bunch of code).
> Request builder

- package.json
- shell.go
- shell_test.go
I needed a couple commands, so i implemented them:
- swarm peers
- stats bw
I wanted a general way to issue commands to be exported,
so i added that. As described in #92
> Request, RequestDecode, swarm peers, stats bw

- request.go
Small change that can help debug a response received with an unsupported content type header (or with no header), or that can't be read or unmarshalled, by logging the HTTP status code in the error messages.
> Log HTTP status code when receiving response with unexpected encoding

- request.go
RequestBuilder allows you to specify headers. These are passed all the way down to the Send() method in request.go, but then they are not added to the actual http request. This pull request adds those headers. I need this to add an auth header.
> Add Headers that were specified in the RequestBuilder.

- package.json
- pubsub.go
- shell_test.go
We don't actually need to use the struct definitions from go-libp2p-pubsub. The interface is part of the API so we should be able to just re-implement them here.
This *is* a breaking change: I've removed the interface and replaced it with a bare struct. IMO, that's *significantly* more idiomatic. `SeqNo()` needed to be changed *anyways* as we can't guarantee that sequence numbers are *just* numbers, they can be anything. The existing code would have crashed when run against js-ipfs, as far as I could tell.
> remove the go-libp2p-pubsub dependency

- dag.go
- package.json
- request.go
- shell.go
Apparently breaking code breaks gx on jenkins
> gx: update to use extracted go-ipfs-files

- shell.go
In `Shell::Create` you can specify whether or not to create intermediary nodes. At the moment, instead of letting the user toggle whether or not to create them, it defaults to `true`, this allows the user to decide whether or not to create, as opposed to the current hard-coded `true`.
> shell: pass in create instead of hard-code

- shell_test.go
While writing this test, it became apparent that whether or not you create intermediary nodes, the resulting root hash is the same. What exactly is the effect of creating/not-creating the intermediary nodes? If there is a big difference I should be able to expand the test to check whether or not the intermediary nodes were created, however I'm not quite able to ascertain what the difference is.
Adds a test for [pull/143](https://github.com/ipfs/go-ipfs-api/pull/143)
> Add Test for PatchLink for create == false

- .gx/lastpubver
- add.go
- dag.go
- package.json
- shell.go
Depends on https://github.com/ipfs/go-ipfs-files/pull/2
> Update go-ipfs-files to 2.0

- pubsub.go
- shell_test.go
Otherwise, we cast the base64 encoded string to a peer ID (which isn't valid).
> correctly decode the peer ID

- requestbuilder.go
- shell.go
- shell_test.go
Unfortunately, we can't handle redirects as we may have read from some request
body and can't start over. This disables redirects and informs the user.
fixes #159
> error on redirect

- request.go
- requestbuilder.go
We return trailing errors from the reader.
> handle late errors when ignoring the response value

- request.go
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#As_a_response_header_for_the_main_body), parameters in the `Content-Disposition` HTTP header must be separated by a `;`.  `go-ipfs-api` use a `:` most likely a typo.
This break the parsing of `multipart/form-data` requests (say, `ipfs add`) with common HTTP library, one of them being golang's `http` package.
> Fix Content-Disposition HTTP header

- request.go
use context to call http client, so can cancel it as need.
> http api to support cancel

- logger.go
- logger_test.go
I needed this functionality to be able to tail ipfs logs for another project and figured it would probably be useful to others.
I tried using the built in request builder, however it appears that it just continually waits for the call to finish, and given that the `log/tail` call streams responses, so it just hangs.
> Add Log Tail Wrapper

- add.go
- shell_test.go
Enables the selection of the multihash type via an `AddOpts` type called `Hash`.
> Enable Multihash Selection When Using Add

- .travis.yml
- shell_test.go
~Do not merge yet, trying out a suspected fix(es) to travis builds~ Good to merge/review
edit: Aha!! I've traced the source of issues, it is the way the docker container is started like this
```
docker run -d -v /tmp/ipfs:/data/ipfs -p 8080:8080 -p 4001:4001 -p 5001:5001 ipfs/go-ipfs:master "--enable-pubsub-experiment"
```
it is unclear in travis that this is what's causing the issue, because you can't actually inspect the state of a docker container. However, running `docker logs <container-id>` gives the following
```
Changing user to ipfs
ipfs version 0.4.21-rc2
Found IPFS fs-repo at /data/ipfs
Error: unknown option "enable-pubsub-experiment"
```
so the reason for failing tests is quite simple actually, there is no ipfs daemon!
> Fix Travis Builds

- pubsub.go
- shell.go
The decoder buffers internally.
> fix decoding json streams

- .travis.yml
- go.mod
- shell.go
- shell_test.go
Add uds support to shell, in order to have something like 
`shell := NewShell("/unix//tmp/sock")`  working
I don't know if it's really pertinent, but I add a simple test that try to create a shell with `/unix/<sockpath>` and make a request to a simple http server listening on the same sock.
I also manually tested the shell against a real ipfs node with:
```diff
modified   shell_test.go
@@ -18,7 +18,7 @@ import (
-	shellUrl     = "localhost:5001"
+	shellUrl     = "/unix//tmp/sock"
)
```
and using `/unix//tmp/sock` as IPFS API listener
> Add Unix Domain Socket support to Shell client

- shell.go
- shell_test.go
This PR add support for the new `pin ls --stream`, see https://github.com/ipfs/go-ipfs/pull/6493
> pin ls --stream support

- README.md
- Fix broken link to github spec
- Include a link to HTTP API
> Fix broken link + add link to HTTP API

- shell.go
- shell_test.go
Close #237 
I was thinking about ways to restrict the possible values for `PinType`, but could not come up with any nice ways, any suggestions would be appreciated.  
Also did not add check for restricting values of `PinType` in `PinsOfType`, because API returns with a very descriptive error for invalid `PinType` values.
> Added Type field for Pin ls command

- dag.go
- options/dag.go
Updates to match https://github.com/ipfs/go-ipfs/pull/8439
> Update dag put flags

- .github/actions/go-test-setup/action.yml
- README.md
- go.mod
- go.sum
- pubsub.go
- shell.go
- shell_test.go
This updates HTTP RPC wire format to one from https://github.com/ipfs/go-ipfs/pull/8183
- peerid uses default text representation from go-libp2p
- byte fields sent over HTTP RPC are now encoded in multibase
- CI in this repo will become green when above PR lands in go-ipfs@master  – https://github.com/ipfs/go-ipfs-api/blob/master/.github/actions/go-test-setup/action.yml#L9
> feat: pubsub http rpc with multibase

- .github/actions/go-test-setup/action.yml
I want to replace the ipfs init and ipfs daemon calls here with a common action(https://github.com/ipfs/start-ipfs-daemon-action) to minimise duplication. This is part of work related to this issue: https://github.com/ipfs/go-ipfs/issues/8511
The workflow passes after the changes introduced by me: https://github.com/ipfs/go-ipfs-api/actions/runs/1579095670
> chore: use common ipfs/start-ipfs-daemon-action in go-test-setup

- shell.go
- shell_test.go
This PR adds the [/swarm/peering/ls](https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-swarm-peering-ls) and [/swarm/peering/add](https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-swarm-peering-add) commands. I'm working on a project where these commands would be really useful so putting this PR up for consideration.
In order to test, I pulled down [ipfs/kubo](https://github.com/ipfs/kubo), ran `docker compose up`, and ran the `shell_test.go` against the container.
> Add ls and add swarming commands

- pubsub.go
Topic is appending after the length of topics in the slice, causing it to waste space.
> fix: topic list append

- add.go
- shell_test.go
This PR modifies the AddDir function to accept AddOpts. A test function in `shell_test.go` called TestAddDirWithCidV1 has been included to ensure that CidVersion(1) works as an AddOpt.
See https://github.com/ipfs/go-ipfs-api/issues/276 for reference issue
> feat: add options to AddDir

- mfs.go
- mfs_test.go
Hi, I noticed an option is missing so I've added it. If you consider this useful, please accept this PR
Signed-off-by: vkost <viktor.kostadinov@gmail.com>
> feat: add missing "parents" option to FilesCp command

- dag.go
- go.mod
- options/dag_stat.go
- shell_test.go
As requested in [#286 ](https://github.com/ipfs/go-ipfs-api/issues/286), this PR includes `DagStat` method along with the Test functions.
> Feat: add dag stat method
